<?php defined('SYSPATH') or die('No direct script access.');
/**
* @Category Label Language File(English)
* @This file contains english language id's for Guest module which will get used in moslty not frequently changable sentences
* @author    Roopam
* @Package Guest
* @Date      10-July-2015
*/
return array(
'ADD_NOTES' => 'Add Notes',
'IMPORT_GUESTS' => 'Import Guests',
'TOTAL_RECORDS' => 'Total Records',
'NAME' => 'Name',
'GUEST_TYPE' => 'Guest Type',
'EMAIL' => 'Email',
'GUEST' => 'Guest',
'STATUS' => 'Status',
'EDIT' => 'Edit',
'ADD' => 'Add',
'ADDED' => 'Added',
'DELETE' => 'Delete',
'PRINT' => 'Print',
'EXPORT' => 'Export To Excel',
'GUEST_DETAILS' => 'Guest Details',
'FIRST_NAME' => 'First Name',
'LAST_NAME' => 'Last Name',
'E_MAIL' => 'E-mail',
'CELL_PHONE' => 'Cell Phone',
'GUEST_OF'  => 'Guest Of',
'NOTES' => 'Notes',
'SAVE_ADD_NEW' => 'Save & Add Another ',
'SAVE' => 'Save',
'CLOSE' => 'Close',
'CANCEL' => 'Cancel',
'EMPTY_TEXT' => 'Select Photo...',
'SELECT_PHOTO' => 'Select Photo',
'QUICK_SEARCH' => 'Quick Search',
'SEARCH_TYPE'  => 'Search Type',
'EMPTY_SEARCH_TYPE'  => 'Empty Search Type',
'EMPTY_SEARCH_VALUE' => 'Empty Search Value',
'SEARCH' => 'Search',
'RESET' => 'Reset',
'ENTER_FOR_SEARCH' => 'Enter for search...',
'NOTHING_FOUND' => 'Nothing Found',
'SELECT_GUEST_TYPE' => 'Select guest type',
'ENABLED' => 'Enabled',
'ENABLE' => 'Enable',
'DISABLED' => 'Disabled',
'DISABLE' => 'Disable',
'BLANK_FIRST_NAME' => 'First Name is required',
'BLANK_LAST_NAME' => 'Last Name is required',
'YES' => 'Yes',
'NO' => 'No',
'NO_RECORD_FOUND' => 'No Records Found',
'NO_NOTES_ADDED' => 'No Notes Added',
'RESET_GRID' => 'Reset Grid Settings',
'CLEAR_GRID_COLUMN_FILTER'   => 'Clear Column Filters',
'SELECT_FILE' => 'Select file',
'IMPORT_EXCEL' => 'Import Excel',
'UPLOAD' => 'Upload',
'LOADING' => 'Loading...',
'NO_DATA_TO_DISPLAY' => 'No data to display',
'AFFILIATION' => 'Affiliation',
'SUBMITTED_BY' => 'Submitted By',
'SUBMITTED_BY_:' => 'Submitted By:',
'APPROVED_BY' => 'Approved By',
'APPROVED_BY_:' => 'Approved By:',
'DATE_APPROVED_:' => 'Date Approved:',
'DATE_APPROVED' => 'Date Approved',

//Alert message.
'CONF_ENABLE_MSG' => 'Are you sure you want to enable status?',
'CONF_DISABLE_MSG' => 'Are you sure you want to disable status?',
'UNABLE_CRED_UPDATED' => 'Fail to change status',
'IMG_DELETE_CONFIRM' => 'Are you sure you want to delete this image?',
'SIGNATURE_DELETE_CONFIRM' => 'Are you sure you want to delete signature?',
'UNABLE_TO_ADD' => 'Unable to add Guest',
'UNABLE_TO_UPDATE' => 'Unable to update Guest',
'UNABLE_TO_ADD_PROTOCOL' => 'Unable to add protocol',
'UNABLE_TO_ADD_NOTE' => 'Unable to add Note',
'UNABLE_TO_ADD_PHOTO' => 'Unable to add Guest Photo',
'FAILED_TO_ACCESS'  => ' Failed To Load Access Template!!!',


//for error log
'NOT_EXCEL_FILE' => 'Not an excel file',
'ERROR' => 'Error',
'TOTAL_RECORDS_UPLOADED'  => 'Total Records uploaded',
'INVALID_FIRST_NAME' => 'Empty first name field',
'INVALID_LAST_NAME' => 'Empty last name field',
'INVALID_EMAIL' => 'Invalid email address',
'INVALID_CELL_PHONE' => 'Invalid cell phone number',
'INVALID_STATUS' => 'Invalid status option',,
'INVALID_DEPARTMENT' => 'Invalid department',
'NO_RECORD_UPLOADED' => 'No records uploaded',
'IMPORT_GUEST_STATUS' => 'Import Guest Status',
'GUEST_NOTES' => 'Guest Notes',
'RECORDS_PER_PAGE' => 'Records Per Page:',
'DEPARTMENT' => 'Department',
'SELECT_DEPARTMENT' => 'Select Department',
'PLEASE_SELECT_DEPARTMENT' => 'Please select department',
'PLEASE_WAIT' => 'Please Wait....',
'WAITING' => 'Waiting...',
'EMPTY_DEPARTMENT' => 'Empty department field',

//Notification
 'FAILED_TO_SAVE' => 'Failed to save',
 'FAILED_TO_UPDATE' => 'Failed to update',
 'FAILED_TO_DELETE' => 'Failed to delete',
 'DELETE_GUEST' => 'Guest deleted successfully',
 'ADD_GUEST' => 'Guest saved successfully',
 'IMG_SIZE_INCORRECT'	=> 'File size must be less than 2 MB',
 'IMG_TYPE_INCORRECT' => 'File must be either JPG,JPEG,GIF or PNG.',
 'IMG_DELETE' => 'Image deleted successfully',
 'UPDATE_GUEST' => 'Guest updated successfully',
 'UPDATE_STATUS' => 'Status updated successfully',
 'IMPORT_RECORDS' => 'Records imported successfully',
 );
